import { appendFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { createInterface } from "node:readline/promises";
import { loadConfig, patchConfig, type SyncChoice } from "../config.js";
import { commitFiles, repoRoot, tryGit } from "../git.js";
import { isPinned, ledgerPath, noteOf, readLedger, verdictOf } from "../ledger/io.js";
import type { DecisionEntry, RatifyEntry } from "../ledger/schema.js";

const START = "<!-- whodecided:precedents (auto-generated by `wdd sync`, do not edit) -->";
const END = "<!-- /whodecided:precedents -->";
const DOC = join(".wdd", "PRECEDENTS.md");

const HEADING = "## Decision precedents (whodecided)";
const INTRO = [
  "Precedents you pinned while reviewing. Follow **DO**, avoid **DON'T**.",
  "Run `wdd recall <term>` for the full decision record.",
];

/** Only decisions the user pinned - not every ruling. */
function precedentLines(entries: DecisionEntry[], ratifies: RatifyEntry[]): string[] {
  const lines: string[] = [];
  for (const e of entries) {
    if (!isPinned(ratifies, e.id)) continue;
    const v = verdictOf(ratifies, e.id);
    const where = e.files?.[0] ? ` — ${e.files[0].split("/").pop()}` : "";
    const note = noteOf(ratifies, e.id); // the user's supplement/refinement to the rule
    const supp = note ? ` — ${note}` : "";
    if (v === "accept") lines.push(`- DO: ${e.what}${where}${supp} [${e.id}]`);
    else if (v === "reject") {
      const alt = e.alternatives?.[0] ? ` (instead: ${e.alternatives[0]})` : "";
      lines.push(`- DON'T: ${e.what}${alt}${where}${supp} [${e.id}]`);
    }
  }
  return lines;
}

function inlineBlock(lines: string[]): string {
  const body = lines.length ? lines.join("\n") : "- (nothing pinned yet - pin the core decisions while reviewing)";
  return [START, HEADING, "", ...INTRO, "", body, END].join("\n");
}

/** link mode: file holds only a reference; the list lives in .wdd/PRECEDENTS.md. */
function linkBlock(targetFile: string): string {
  // CLAUDE.md supports `@path` imports (auto-loaded); other files get a plain
  // link (Codex/AGENTS.md won't auto-load it, so inline is safer there).
  const ref = basename(targetFile) === "CLAUDE.md" ? "@" + DOC : `[decision precedents](${DOC})`;
  return [START, HEADING, "", INTRO[0], "", "See " + ref + " for the ratified DO / DON'T list.", END].join("\n");
}

function docFile(lines: string[]): string {
  const body = lines.length ? lines.join("\n") : "- (nothing pinned yet)";
  return ["# Decision precedents (whodecided)", "", ...INTRO, "", body, ""].join("\n");
}

/** Replace the managed block in place; append if absent; keep all other content. */
function writeBlock(file: string, block: string): void {
  let text = existsSync(file) ? readFileSync(file, "utf8") : "";
  const s = text.indexOf(START);
  const e = text.indexOf(END);
  if (s >= 0 && e > s) text = text.slice(0, s) + block + text.slice(e + END.length);
  else text = (text.trim() ? text.replace(/\n*$/, "\n\n") : "") + block + "\n";
  writeFileSync(file, text);
}

function generate(root: string, choice: SyncChoice): string[] {
  const { entries, ratifies } = readLedger(ledgerPath(root));
  const lines = precedentLines(entries, ratifies);
  const changed: string[] = [];
  if (choice.targets.length === 0) return changed; // "off" — audit only
  if (choice.mode === "link") {
    writeFileSync(join(root, DOC), docFile(lines));
    changed.push(DOC);
  }
  for (const rel of choice.targets) {
    writeBlock(join(root, rel), choice.mode === "link" ? linkBlock(rel) : inlineBlock(lines));
    // A *.local.md destination is personal: keep it out of git, don't touch shared .gitignore.
    if (/\.local\.md$/.test(rel)) excludeLocally(root, rel);
    changed.push(rel);
  }
  return changed;
}

/** git-native local ignore, so the personal memory file never gets committed. */
function excludeLocally(root: string, pattern: string): void {
  const gitDir = tryGit(root, "rev-parse", "--git-dir");
  if (!gitDir) return;
  const exclude = join(gitDir.startsWith("/") ? gitDir : join(root, gitDir), "info", "exclude");
  const existing = existsSync(exclude) ? readFileSync(exclude, "utf8") : "";
  if (new RegExp("^" + pattern.replace(/[.]/g, "\\$&") + "$", "m").test(existing)) return;
  appendFileSync(exclude, (existing.endsWith("\n") || existing === "" ? "" : "\n") + pattern + "\n");
}

/** Regenerate per the recorded choice. Returns changed repo-relative paths (empty if not opted in). */
export function refreshSync(root: string): string[] {
  const choice = loadConfig(root).sync;
  return choice ? generate(root, choice) : [];
}

/**
 * Decide once where precedents sync, and record it. Called at `hook install`
 * so every later ruling auto-syncs with no separate step. Interactive: confirm
 * the detected target; non-interactive: take the smart default silently.
 * Returns the changed files (target written), or [] if the user declined.
 */
export async function configureSync(root: string, interactive: boolean): Promise<string[]> {
  let choice = loadConfig(root).sync;
  if (!choice) {
    choice = interactive ? await ask(root) : { targets: recommend(root).targets, mode: "inline" };
    if (!choice) return [];
    // Record even the "off" choice (empty targets) so we never re-prompt.
    patchConfig(root, { sync: choice });
  }
  return generate(root, choice);
}

export async function sync(args: string[]): Promise<number> {
  const root = repoRoot(process.cwd());
  if (!root) {
    process.stderr.write("wdd sync: not inside a git repo\n");
    return 1;
  }
  const recorded = loadConfig(root).sync;
  const flagTargets = flag(args, "--target");
  const flagMode = flag(args, "--mode");

  let choice: SyncChoice | undefined = recorded;
  if (flagTargets || flagMode) {
    choice = {
      targets: flagTargets ? flagTargets.split(",").map((s) => s.trim()).filter(Boolean) : (recorded?.targets ?? recommend(root).targets),
      mode: flagMode === "link" ? "link" : flagMode === "inline" ? "inline" : (recorded?.mode ?? "inline"),
    };
  } else if (!recorded) {
    if (!process.stdin.isTTY) {
      process.stderr.write(
        "wdd sync: not configured yet. Run interactively once, or pass --target <file[,file]> --mode <inline|link>.\n",
      );
      return 1;
    }
    choice = await ask(root);
    if (!choice) return 1;
  }
  if (!choice) return 1;

  patchConfig(root, { sync: choice });
  if (choice.targets.length === 0) {
    process.stdout.write("precedents won't sync to any file (audit only). Change with wdd sync.\n");
    return 0;
  }
  const changed = generate(root, choice);
  const { entries, ratifies } = readLedger(ledgerPath(root));
  const ruled = entries.filter((e) => verdictOf(ratifies, e.id) !== undefined).length;
  const where = `${choice.targets.join(", ")} (${choice.mode})`;
  const cfg = loadConfig(root);
  if (cfg.share === "repo" && cfg.commit === "on") {
    const sha = commitFiles(root, [...changed, join(".wdd", "config.yaml")], `wdd sync: ${ruled} precedent(s) → ${choice.targets.join(", ")}`);
    process.stdout.write(`${where}: ${ruled} precedent(s)${sha.sha ? ` → commit ${sha.sha}` : ""}\n`);
  } else {
    process.stdout.write(`${where}: ${ruled} precedent(s) written (not committed — commit when you're ready)\n`);
  }
  if (choice.mode === "link" && choice.targets.some((t) => basename(t) !== "CLAUDE.md")) {
    process.stderr.write("note: link mode only auto-loads in CC (CLAUDE.md @import); Codex/AGENTS.md need inline\n");
  }
  process.stdout.write("auto-refreshes on every ruling from now on\n");
  return 0;
}

/**
 * Detect the repo's agent-memory setup and recommend where precedents should
 * go, so one write covers the agents actually in use:
 * - CLAUDE.md imports AGENTS.md  -> AGENTS.md alone (covers CC via import + Codex)
 * - only CLAUDE.md               -> CLAUDE.md (CC)
 * - only AGENTS.md               -> AGENTS.md (Codex, and CC reads it too)
 * - both, not linked             -> both (CC and Codex read different files)
 * - neither                      -> AGENTS.md (cross-agent default)
 */
export function recommend(root: string): { targets: string[]; reason: string } {
  const read = (n: string) => (existsSync(join(root, n)) ? readFileSync(join(root, n), "utf8") : null);
  const claude = read("CLAUDE.md");
  const agents = read("AGENTS.md");
  const claudeImportsAgents = claude != null && /@\.?\/?AGENTS\.md/.test(claude);
  if (agents != null && (claudeImportsAgents || claude == null)) {
    return { targets: ["AGENTS.md"], reason: claudeImportsAgents ? "your CLAUDE.md imports AGENTS.md, so this covers CC and Codex" : "covers Codex (and CC reads AGENTS.md too)" };
  }
  if (claude != null && agents == null) return { targets: ["CLAUDE.md"], reason: "CLAUDE.md is your only agent file" };
  if (claude != null && agents != null) return { targets: ["CLAUDE.md", "AGENTS.md"], reason: "CLAUDE.md does not import AGENTS.md, so both are needed for CC + Codex" };
  return { targets: ["AGENTS.md"], reason: "no agent file yet; AGENTS.md is read by both CC and Codex" };
}

async function ask(root: string): Promise<SyncChoice | undefined> {
  const rec = recommend(root);
  const options: { targets: string[]; label: string }[] = [
    { targets: rec.targets, label: `${rec.targets.join(" + ")}  (recommended, shared — ${rec.reason})` },
    { targets: ["AGENTS.md"], label: "AGENTS.md only (shared, committed)" },
    { targets: ["CLAUDE.md"], label: "CLAUDE.md only (shared, committed)" },
    { targets: ["AGENTS.md", "CLAUDE.md"], label: "AGENTS.md + CLAUDE.md (shared)" },
    { targets: ["CLAUDE.local.md"], label: "CLAUDE.local.md (local, just me — not committed)" },
    { targets: [], label: "don't remember to any file — audit only" },
  ];
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  try {
    process.stdout.write("Where should pinned precedents be written? (agents read these files)\n");
    options.forEach((o, i) => process.stdout.write(`  ${i + 1}) ${o.label}\n`));
    const raw = (await rl.question("choose [1]: ")).trim();
    const idx = raw === "" ? 0 : Number(raw) - 1;
    const pick = options[idx];
    if (!pick) return options[0] ? { targets: options[0].targets, mode: "inline" } : undefined;
    return { targets: pick.targets, mode: "inline" };
  } finally {
    rl.close();
  }
}

function flag(args: string[], name: string): string | undefined {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
}
