import type { GateStatus } from "../checks/gate.js";
import type { DecisionEntry, RatifyEntry } from "../ledger/schema.js";
import type { TestWeakening } from "../checks/diff-signals.js";
import { followups, verdictOf } from "../ledger/io.js";

export function renderMd(
  entries: DecisionEntry[],
  ratifies: RatifyEntry[],
  gate: GateStatus,
  header: string,
  weakened: TestWeakening[] = [],
): string {
  const badge = gate.green ? "🟢 gate: green" : "🔴 gate: red";
  const freshness = gate.fresh ? "ledger fresh" : `undistilled sessions: ${gate.staleSessions.join(", ")}`;
  const fixes = followups(entries, ratifies);
  const lines = [
    `## Decision audit: ${header}`,
    "",
    `${badge} · ${freshness} · ${gate.pendingSilent.length} silent decision(s) pending`,
    "",
  ];
  if (weakened.length > 0) {
    lines.push(`### ⚠ Tests weakened on this branch (${weakened.length})`, "");
    for (const w of weakened) {
      const what = [w.removedTests ? `${w.removedTests} removed` : "", w.addedSkips ? `${w.addedSkips} skipped` : "", w.removedAssertions ? `${w.removedAssertions} assertion(s) dropped` : ""].filter(Boolean).join(", ");
      lines.push(`- \`${w.file}\` — ${what}`);
    }
    lines.push("");
  }
  if (fixes.length > 0) {
    lines.push(`### ⚠ Overturned — code fix pending (${fixes.length})`, "");
    for (const f of fixes) {
      lines.push(`- **${f.entry.id}** ${f.entry.what}${f.correction ? `  <br/><sub>→ ${f.correction}</sub>` : ""}`);
    }
    lines.push("");
  }
  section(lines, ratifies, "⚠ Silent agent decisions", entries.filter((e) => e.by === "agent" && !e.aware));
  section(lines, ratifies, "⚠ Your reflexive decisions", entries.filter((e) => e.by === "user" && !e.aware));
  section(lines, ratifies, "✓ Your deliberate decisions", entries.filter((e) => e.aware));
  lines.push(`_generated by [whodecided](https://github.com/zhu-kai/whodecided) · \`wdd report --md\`_`);
  return lines.join("\n");
}

function section(lines: string[], ratifies: RatifyEntry[], title: string, entries: DecisionEntry[]): void {
  if (entries.length === 0) return;
  lines.push(`### ${title} (${entries.length})`, "");
  for (const e of entries) {
    const verdict = verdictOf(ratifies, e.id);
    const mark = verdict === "accept" ? "✅" : verdict === "reject" ? "❌" : "⏳";
    const detail = [e.why, e.alternatives?.length ? `alt: ${e.alternatives.join(", ")}` : "", e.reversibility === "low" ? "hard to reverse" : ""]
      .filter(Boolean)
      .join(" · ");
    lines.push(`- ${mark} **${e.id}** ${e.what}${detail ? `  <br/><sub>${detail}</sub>` : ""}`);
  }
  lines.push("");
}
